In [1041]:
import pandas as pd
import numpy as np

In [1042]:
pd.set_option('max_columns', 40)
pd.set_option('max_colwidth', 5000)

In [1043]:
df_crash = pd.read_csv("data_100000.csv", sep=',')

In [1044]:
df_crash.crash_date = df_crash.crash_date.astype('datetime64[ns]')

In [1045]:
df_crash.crash_time = df_crash.crash_time.astype('datetime64[ns]')

In [1046]:
df_crash['crash_year'] = df_crash.crash_date.dt.year
df_crash['crash_month'] = df_crash.crash_date.dt.month
df_crash['crash_day'] = df_crash.crash_date.dt.day
df_crash['crash_hour'] = df_crash.crash_time.dt.hour
df_crash['crash_minute'] = df_crash.crash_time.dt.minute

In [1047]:
df_crash = df_crash.drop(columns=['crash_date', 'crash_time', 'location'])

In [1048]:
df_crash.duplicated().any()

False

In [1049]:
lower_list = ['borough', 'on_street_name', 'off_street_name', 'cross_street_name', 'contributing_factor_vehicle_1', 'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3', 'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5', 'vehicle_type_code1', 'vehicle_type_code2', 'vehicle_type_code_3', 'vehicle_type_code_4', 'vehicle_type_code_5']

def to_lower(column_name:str):
    df_crash[column_name] = df_crash[column_name].apply(lambda x:x.lower() if type(x) == str else x)
    return df_crash[column_name]

for column_name in lower_list:
    df_crash[column_name] = to_lower(column_name)

In [1050]:
df_crash = df_crash.rename(columns={'vehicle_type_code1': 'vehicle_type_1', 'vehicle_type_code2': 'vehicle_type_2', 'vehicle_type_code_3': 'vehicle_type_3', 'vehicle_type_code_4': 'vehicle_type_4', 'vehicle_type_code_5': 'vehicle_type_5'})

In [1051]:
df_crash.vehicle_type_1.value_counts()

sedan                                  46790
station wagon/sport utility vehicle    35766
taxi                                    3479
pick-up truck                           2616
box truck                               1952
                                       ...
pumper                                     1
front-load                                 1
nys a                                      1
e skate bo                                 1
freig                                      1
Name: vehicle_type_1, Length: 281, dtype: int64

In [1052]:
df_crash = df_crash.set_index(df_crash.collision_id)

In [1053]:
fill_locations = ['on_street_name', 'off_street_name', 'cross_street_name', 'borough']

for col_name in  fill_locations:
    df_crash[col_name] = df_crash[col_name].fillna('unknown')

In [1054]:
df_crash =  df_crash.drop(columns=['collision_id'])

In [1055]:
df_crash = df_crash.sort_index(ascending=True)

In [1056]:
factor_fill = ['contributing_factor_vehicle_1', 'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3', 'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5']

for col_name in factor_fill:
    df_crash[col_name] = df_crash[col_name].fillna('not applicable')

In [1057]:
df_crash.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 2568 to 4353706
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   borough                        100000 non-null  object
 1   zip_code                       64966 non-null   float64
 2   latitude                       91965 non-null   float64
 3   longitude                      91965 non-null   float64
 4   on_street_name                 100000 non-null  object
 5   off_street_name                100000 non-null  object
 6   cross_street_name              100000 non-null  object
 7   number_of_persons_injured      100000 non-null  int64
 8   number_of_persons_killed       100000 non-null  int64
 9   number_of_pedestrians_injured  100000 non-null  int64
 10  number_of_pedestrians_killed   100000 non-null  int64
 11  number_of_cyclist_injured      100000 non-null  int64
 12  number_of_cyclist_killed       100000 non-null  int64
 13  number_of_motorist_injured     100000 non-null  int64
 14  number_of_motorist_killed      100000 non-null  int64
 15  contributing_factor_vehicle_1  100000 non-null  object
 16  contributing_factor_vehicle_2  100000 non-null  object
 17  contributing_factor_vehicle_3  100000 non-null  object
 18  contributing_factor_vehicle_4  100000 non-null  object
 19  contributing_factor_vehicle_5  100000 non-null  object
 20  vehicle_type_1                 99260 non-null   object
 21  vehicle_type_2                 73411 non-null   object
 22  vehicle_type_3                 8329 non-null    object
 23  vehicle_type_4                 2147 non-null    object
 24  vehicle_type_5                 646 non-null     object
 25  crash_year                     100000 non-null  int64
 26  crash_month                    100000 non-null  int64
 27  crash_day                      100000 non-null  int64
 28  crash_hour                     100000 non-null  int64
 29  crash_minute                   100000 non-null  int64
dtypes: float64(3), int64(13), object(14)
memory usage: 23.7+ MB

In [1058]:
vehicle_fill = ['vehicle_type_1', 'vehicle_type_2', 'vehicle_type_3', 'vehicle_type_4', 'vehicle_type_5']

for col_name in vehicle_fill:
    df_crash[col_name] = df_crash[col_name].fillna('not applicable')

In [1059]:
vehicle_list = ['ATV(all_terrain_vehicle)', 'bicycle', 'car/suv', 'ebike / escooter', 'truck/bus', 'motorcycle', 'other']

In [1060]:
vehicle_list = ['vehicle_type_1', 'vehicle_type_2',	'vehicle_type_3', 'vehicle_type_4', 'vehicle_type_5']

def consolidate(col_name):
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambul', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='amb', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambu', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='fdny ambul', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='nyc ambula', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambulence', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='abulance', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='almbulance', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambulence', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='white ambu', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='gen  ambul', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='abulace', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='leased amb', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambulace', value='ambulance')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash[col_name] = consolidate(col_name)

In [1061]:
replace_list = ['bus','van camper','box truck','tractor truck diesel','dump','tractor truck gasoline','tow truck / wrecker','concrete mixer','tract','beverage truck','refg', 'refrigerated van', 'box t', 'tanker', 'unkno', '4ds', 'com', 'armored truck', 'ladder 34','chassis cab','school bus','bulk agriculture', 'tower', 'self', 'truck', 'fire', 'white','trac', 'trail', 'open body','enclosed body - nonremovable enclosure', 'us po', 'usps', 'schoo','bulld', 'range', 'mta', 'well driller', 'picku', 'appor','fdny', 'lunch wagon', 'multi-wheeled vehicle', 'excav', 'nys a','firet', 'dirt', 'tow t','mta b','tow truck', 'uhaul', 'trl', 'back', 'towtr', 'sprin','trk', 'tk', 'fork', 'city', 'power', 'van t', 'mobil','comme', 'trlr','motorized home', 'cont', 'pickup with mounted camper', 'g spc', 'wineb', 'ltr', 'parce', 'forkl', 'hi ta','boxtr', 'pedicab', '35 ft', 'ut', 'backh', 'cat.', 'pu', 'const','prks', 'rmp v', 'paylo','flat', 'fdny truck','usps posta', 'firetruck','freight tr','freig delv', 'pc', 'mail truck','usps truck', 'fire truck', 'postal tru', 'commercial','fdny fire', 'enclosed body - removable enclosure','work van', 'lcomm', 'freig', 'government', 'subn whi','flatbed','camper tra', 'trailer','hrse', 'ems', 'back hoe', 'light trai','cargo van', 'f-250','fork lift', 'unk', 'trc', 'postal bus', 'nyc fd','f150xl pic', 'fire engin', 'mta bus', 'unknown','elec. unic', '1c', 'delivery t', 'gator', 'fdny engin','freight', 'ups truck','slingshot', 'road sweep','delivery v', 'utility ve', 'bucket tru', 'backhoe', 'tractor','moving van', '18 wheeler', 'usps van', 'garbage tr','livestock rack', 'freight fl', 'fdny #226', 'cross', 'food truck', 'dump truck','front-load', 'pumper','truck flat', 'tractor tr', 'delivery','truck van', 'psd', 'courier', 'swt', 'dilevery t','ford van', 'dark color','power shov', 'fdny ems','usps/govt', 'flatbed fr', 'can', 'cement tru', 'firtruck', 'f550','fdny ladde', 'box', 'livery vehicle','van', 'pick-up truck','polic', 'food', 'carry all','rv', 'garbage or refuse', 'p/sh', 'flat bed', 'cemen', 'delv', 'pk', 'intl', 'tuck', 'deliv','pas', 'moped', 'garba', 'enclo', 'movin', 'hand','uspos', 'stree', 'elect', 'post', 'hopper','campe', 'flat rack', 'dp', 'van (', 'fed e','glass rack', 'vanette', 'engin', 'work','jlg l', 'black','alumi','churc', 'utili','dirtb', 'rep', 'mack','pass', 'snow plow', 'ip', 'yello', 'trans', 'tra/r','detac', 'aspha', 'art m', 'mail', 'util wh', 'depar', 'spec-','ladder tru', 'schoolbus', '18 weeler', 'glnen', 'sweeper','tl', 'fd truck', 'sanitation', 'cargo truc', 'itas', 'lcom', 'hearse','frt', 'mailtruck', 'lma','skid loade','utility tr', 'tree cutte','van/transi', 'glp050vxev', 'ice cream', 'mobile', 'haul for h', 'commerical', 'freightlin', 'mopd','ems truck', 'nyc bus', 'us govt ve', 'special pu', 'frieghtlin', 'palfinger','internatio', 'fdny firet', 'mta truck','street cle','nyc firetr', 'moped elec', 'street swe','uhaul truc', 'u-haul', 'truck trai', 'tilt tande', 'revel', 'backhoe lo', 'transport','amazon spr','mini van', 'i1', 'fleet', 'constructi','left the s', 'nyc acs va', 'boom lift''carry all', 'van', 'garbage or refuse''moped', 'flat bed','food', 'pk', 'deliv','fdny firet', 'uhaul trai','uhaul box', 'unattached', 'concrete m', 'flat rack']
def trucks_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'truck/bus')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = trucks_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = trucks_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = trucks_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = trucks_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = trucks_cons('vehicle_type_5')

In [1062]:
replace_list = ['passenger vehicle', 'sport utility / station wagon', 'taxi','small com veh(4 tires) ', 'sedan','station wagon/sport utility vehicle', 'not applicable', 'bike','convertible','util','4d', '4 dr sedan', '2 dr sedan','3-door', 'e-350', 'comm.', 'bs','limou', 'mini', 'limo', 'e450', 'utility.','chevrolet', 'fusion','j1','chevy expr', 'ford sprin', 'wh ford co','unkn', 'suburban', 'oth''forlift', 'utility', 'smart car','sport utility / station wagon','passenger vehicle', 'taxi','small com veh(4 tires) ', 'station wagon/sport utility vehicle','sedan', '3-door', 'convertible','4 dr sedan','wagon', 'self-', 'ford','limo','util','2 dr sedan', 'rds','access a r', 'toyota', 'vehicle 2', 'ukn','passenger vehicle', 'taxi', 'sedan','station wagon/sport utility vehicle','convertible','4 dr sedan', 'limo', '3-door','sport utility / station wagon','station wagon/sport utility vehicle', 'sedan','taxi', 'convertible','toyot','4 dr sedan','limo','sedan', 'station wagon/sport utility vehicle','taxi','convertible', 'wagon']
def cars_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'car/suv')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = cars_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = cars_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = cars_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = cars_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = cars_cons('vehicle_type_5')

In [1063]:
replace_list = ['btm','minibike', 'scoot', 'stake or rack', 'minicycle', 'e-bik','e-sco', 'e bik', 'e-bike', 'dirt bike','e-scooter', 'e bike','e skate bo', '0', 'electric s', 'scooter', 'e revel sc', 'motor scoo', 'motorscoot', 'skateboard','message si', 'motor skat','e-unicycle','minibike', 'motorscooter', 'e-bik','scoot', 'e bik', 'e-sco','minicycle', 'stake or rack', 'e sco', 'skate','e350', 'subn', 'e250','e-ska', 'e-scooter', 'ebike', 'e-bike', 'scooter', 'c1', 'e-scoter', 'dirt bike','push scoot','gas scoote','razor scoo','e-skateboa', 'electric s', 'escooter','moped scoo', 'electric m', 'skateboard', 'dirtbike', 'uknown', 'e scooter', 'unknown ve', 'motor scoo','motorcycle', 'motorscooter', 'e-bik', 'e-bike', 'e-scooter','stake or rack','motorscooter','e-scooter','e-bike','e-scooter','motorscooter']
def bikes_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'ebike / escooter')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = bikes_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = bikes_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = bikes_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = bikes_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = bikes_cons('vehicle_type_5')

In [1064]:
replace_list = ['motorbike', 'vespa', 'motor', 'motorbike','motorbike']
def motorbike_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'motorbike')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = motorbike_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = motorbike_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = motorbike_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = motorbike_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = motorbike_cons('vehicle_type_5')

In [1065]:

replace_list = ['pick-','pick up tr', 'pick-up tr', 'pick up','suv','pick','pick up','pick-up tr','pickup', 'suv', 'pick truck', 'ram','4dsd','pick up tr', 'trailor', 'flatbed tr']
def atv_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'atv')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = atv_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = atv_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = atv_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = atv_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = atv_cons('vehicle_type_5')

In [1066]:
replace_list = ['other','posta', 'lift boom', 'winne', 'bobca', 'golf','golf cart', 'forklift', 'mechanical', 'cat', 'fd ladder','bobcat for', 'horse', 'dot equipm', 'go kart', 'john deere','oth', 'drill rig', 'lawnmower', 'forlift','lift boom', 'bobca', 'atv', 'crane', 'pallet','john', 'cat32', 'train', 'lift', 'boom', 'horse', 'golf cart','forklift', 't630 forkl', 'jetski', 'bob cat', 'escovator','john deere', 'lawn mower', 'folk lift', 'boom lift','lift boom', 'pallet']
def other_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'other')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = other_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = other_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = other_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = other_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = other_cons('vehicle_type_5')

In [1067]:
df_crash.vehicle_type_1.unique()

array(['car/suv', 'other', 'truck/bus', 'ebike / escooter', 'ambulance',
       'motorbike'], dtype=object)

In [1068]:
df_crash.vehicle_type_2.unique()

array(['car/suv', 'other', 'truck/bus', 'ebike / escooter', 'ambulance',
       'motorbike'], dtype=object)

In [1069]:
df_crash.vehicle_type_3.unique()

array(['car/suv', 'truck/bus', 'ebike / escooter', 'motorbike',
       'ambulance', 'other'], dtype=object)

In [1070]:
df_crash.vehicle_type_4.unique()

array(['car/suv', 'other', 'truck/bus', 'ebike / escooter', 'ambulance'],
      dtype=object)

In [1071]:
df_crash.vehicle_type_5.unique()

array(['car/suv', 'truck/bus', 'ambulance', 'ebike / escooter'],
      dtype=object)

In [1072]:
df_crash.tail()

,borough,zip_code,latitude,longitude,on_street_name,off_street_name,cross_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,vehicle_type_1,vehicle_type_2,vehicle_type_3,vehicle_type_4,vehicle_type_5,crash_year,crash_month,crash_day,crash_hour,crash_minute
collision_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4353663,brooklyn,11201.0,40.689830,-73.978630,de kalb avenue,ashland place,unknown,1,0,0,0,1,0,0,0,driver inattention/distraction,driver inattention/distraction,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,21,8,55
4353672,brooklyn,11236.0,40.645958,-73.906130,unknown,unknown,992 east 95 street,0,0,0,0,0,0,0,0,driver inattention/distraction,unspecified,unspecified,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,29,16,0
4353701,manhattan,10029.0,NaN,NaN,east 99 street,lexington avenue,unknown,1,0,0,0,1,0,0,0,traffic control disregarded,unspecified,not applicable,not applicable,not applicable,car/suv,ebike / escooter,car/suv,car/suv,car/suv,2020,9,29,19,11
4353705,bronx,10461.0,40.849342,-73.850610,unknown,unknown,1716 williamsbridge road,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,29,14,0
4353706,unknown,NaN,40.790623,-73.942444,2 avenue,unknown,unknown,1,0,0,0,0,0,1,0,following too closely,unspecified,unspecified,unspecified,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,24,18,30

In [1073]:
replace_list = ['contributing_factor_vehicle_1', 'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3', 'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5']

distraction = ['driver inattention/distraction','passenger distraction','fell asleep','outside car distraction',
                   'fatigued/drowsy','cell phone (hand-held)','using on board navigation device',
                   'tinted windows','eating or drinking', 'other electronic device', 'cell phone (hands-free)',
                   'listening/using headphones']
driver_mistake = ['following too closely','failure to yield right-of-way','backing unsafely',
                      'passing or lane usage improper','passing too closely','unsafe lane changing',
                      'turning improperly','driver inexperience', 'failure to keep right',
                      'driverless/runaway vehicle', 'oversized vehicle']
illegal_action = ['unsafe speed','alcohol involvement','traffic control disregarded','aggressive driving/road rage',
                      'drugs (illegal)']
other_involvement =  ['other vehicular','reaction to uninvolved vehicle', 'animals action',
                          'view obstructed/limited','pedestrian/bicyclist/other pedestrian error/confusion',
                           'glare','vehicle vandalism']
bad_road_infrastructure = ['pavement slippery', 'obstruction/debris','pavement defective',
                               'other lighting defects']
car_failures = ['brakes defective', 'steering failure', 'tire failure/inadequate',
                    'traffic control device improper/non-working', 'lane marking improper/inadequate',
                    'tow hitch defective','headlights defective', 'shoulders defective/improper',
                    'windshield inadequate']
medical = ['lost consciousness', 'illnes','accelerator defective','physical disability','prescription medication']

def factor_replace(col_name):
    df_crash[col_name] = df_crash[col_name].replace(distraction, 'distraction')
    df_crash[col_name] = df_crash[col_name].replace(driver_mistake, 'driver_mistake')
    df_crash[col_name] = df_crash[col_name].replace(illegal_action, 'illegal_action')
    df_crash[col_name] = df_crash[col_name].replace(other_involvement, 'other_involvement')
    df_crash[col_name] = df_crash[col_name].replace(bad_road_infrastructure, 'bad_road_infrastructure')
    df_crash[col_name] = df_crash[col_name].replace(car_failures, 'car_failures')
    df_crash[col_name] = df_crash[col_name].replace(medical, 'medical')
    return df_crash[col_name]

for col_name in replace_list:
    df_crash[col_name] = factor_replace(col_name)

In [1074]:
df_crash.head(50)

,borough,zip_code,latitude,longitude,on_street_name,off_street_name,cross_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,vehicle_type_1,vehicle_type_2,vehicle_type_3,vehicle_type_4,vehicle_type_5,crash_year,crash_month,crash_day,crash_hour,crash_minute
collision_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2568,unknown,NaN,NaN,NaN,canal street,washington street,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,5,5,11,32
69010,unknown,NaN,NaN,NaN,edgecombe avenue,west 155 street,unknown,1,0,0,0,0,0,1,0,other_involvement,other_involvement,not applicable,not applicable,not applicable,car/suv,other,car/suv,car/suv,car/suv,2013,4,19,12,5
74294,unknown,NaN,NaN,NaN,bruckner boulevard,east 138 street,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,truck/bus,car/suv,car/suv,car/suv,2013,4,24,18,30
127733,unknown,NaN,NaN,NaN,flatbush avenue,avenue k,unknown,1,0,0,0,0,0,1,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,other,car/suv,car/suv,car/suv,2013,4,29,16,50
210591,unknown,NaN,NaN,NaN,merrick boulevard,108 avenue,unknown,0,0,0,0,0,0,0,0,driver_mistake,unspecified,not applicable,not applicable,not applicable,car/suv,other,car/suv,car/suv,car/suv,2013,4,10,16,0
225766,queens,11004.0,40.746435,-73.703790,268 street,80 avenue,unknown,1,0,1,0,0,0,0,0,unspecified,not applicable,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,10,15,18,0
241823,unknown,NaN,NaN,NaN,northern boulevard,54 street,unknown,4,0,0,0,0,0,4,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,13,12,20
249898,unknown,NaN,NaN,NaN,utopia parkway,cross island parkway s svc rd,unknown,1,0,0,0,0,0,1,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,16,15,40
275704,unknown,NaN,NaN,NaN,astoria blvd north,31 street,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,16,22,30
281939,unknown,NaN,NaN,NaN,astoria boulevard,77 street,unknown,1,0,0,0,0,0,1,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,29,12,15
297595,unknown,NaN,NaN,NaN,unknown,unknown,p/l of 1750 hylan blvd,0,0,0,0,0,0,0,0,driver_mistake,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,21,15,45
2809808,bronx,10469.0,40.869761,-73.844877,east gun hill road,knapp street,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,other,other,car/suv,car/suv,car/suv,2014,10,17,19,27
2874775,unknown,NaN,40.862498,-73.934185,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,truck/bus,car/suv,car/suv,car/suv,2013,4,23,22,20
2879367,unknown,NaN,40.808193,-73.904886,unknown,unknown,unknown,0,0,0,0,0,0,0,0,other_involvement,unspecified,not applicable,not applicable,not applicable,car/suv,truck/bus,car/suv,car/suv,car/suv,2013,4,13,17,40
2912981,unknown,NaN,40.860198,-73.828790,unknown,unknown,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,truck/bus,car/suv,car/suv,car/suv,car/suv,2013,3,23,21,20
2957510,unknown,NaN,40.614812,-74.039816,unknown,unknown,unknown,5,0,0,0,0,0,5,0,other_involvement,other_involvement,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,3,24,5,30
2976167,unknown,NaN,40.678100,-74.002339,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,14,12,30
2983434,unknown,NaN,NaN,NaN,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,unspecified,unspecified,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,21,16,10
3017476,unknown,NaN,40.665840,-73.757385,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,4,22,10,44
3056281,unknown,NaN,NaN,NaN,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2013,5,4,16,0
3205748,unknown,NaN,NaN,NaN,bruckner boulevard,east 138 street,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,4,20,7,0
3208083,unknown,NaN,NaN,NaN,richmond avenue,genesee avenue,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,truck/bus,car/suv,car/suv,car/suv,car/suv,2015,4,22,19,0
3210926,unknown,NaN,NaN,NaN,unknown,unknown,f/o 3138 richmond terrace,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,truck/bus,car/suv,car/suv,car/suv,2015,4,27,20,32
3216273,unknown,NaN,NaN,NaN,jamaica avenue,van wyck expressway,unknown,0,0,0,0,0,0,0,0,other_involvement,other_involvement,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,5,6,17,30
3222266,unknown,NaN,40.781667,-73.986689,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,5,15,18,50
3224230,unknown,NaN,40.851501,-73.942523,unknown,unknown,unknown,0,0,0,0,0,0,0,0,distraction,not applicable,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,5,16,4,15
3224943,unknown,NaN,NaN,NaN,82 street,4 avenue,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,truck/bus,car/suv,car/suv,car/suv,2015,5,21,8,35
3231664,unknown,NaN,NaN,NaN,flatbush avenue,glenwood road,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,1,10,40
3236931,unknown,NaN,40.666539,-73.809943,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,9,16,0
3241488,unknown,NaN,NaN,NaN,horace harding expressway,parsons boulevard,unknown,0,0,0,0,0,0,0,0,driver_mistake,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,17,8,55
3241507,unknown,NaN,40.736323,-73.856302,unknown,unknown,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,17,0,10
3243365,unknown,NaN,40.785032,-73.940571,unknown,unknown,unknown,1,0,0,0,0,0,1,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,18,17,5
3243866,unknown,NaN,NaN,NaN,108 street,horace harding expressway,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,18,16,32
3244540,unknown,NaN,NaN,NaN,west alley road,douglaston parkway,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,22,20,30
3245871,unknown,NaN,40.666502,-73.996189,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,truck/bus,car/suv,car/suv,car/suv,car/suv,2015,6,23,12,40
3246554,unknown,NaN,NaN,NaN,6 street,7 avenue,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,24,16,53
3247283,unknown,NaN,40.735930,-73.723131,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,25,18,0
3247648,unknown,NaN,40.840839,-73.872570,unknown,unknown,unknown,1,0,0,0,0,0,1,0,distraction,unspecified,not applicable,not applicable,not applicable,ebike / escooter,truck/bus,car/suv,car/suv,car/suv,2015,6,26,9,30
3248179,unknown,NaN,NaN,NaN,morrison avenue,bruckner boulevard,unknown,1,0,0,0,0,0,1,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,27,9,0
3248504,unknown,NaN,NaN,NaN,union turnpike,141 street,unknown,0,0,0,0,0,0,0,0,medical,bad_road_infrastructure,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,27,16,45
3249241,unknown,NaN,NaN,NaN,104 street,roosevelt avenue,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,ambulance,car/suv,car/suv,car/suv,car/suv,2015,6,24,19,35
3249984,unknown,NaN,40.733610,-73.923840,unknown,unknown,unknown,0,0,0,0,0,0,0,0,distraction,distraction,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,6,30,14,15
3251048,unknown,NaN,NaN,NaN,3 avenue,91 street,unknown,1,0,0,0,0,0,1,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,ebike / escooter,car/suv,car/suv,car/suv,2015,7,2,10,35
3251201,unknown,NaN,NaN,NaN,metro avenue,flushing avenue,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,truck/bus,car/suv,car/suv,car/suv,car/suv,2015,6,30,15,15
3251252,unknown,NaN,NaN,NaN,unknown,unknown,parking lot of 204-01 hillside avenue,0,0,0,0,0,0,0,0,other_involvement,distraction,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,7,1,12,43
3251851,unknown,NaN,NaN,NaN,union turnpike,austin street,unknown,0,0,0,0,0,0,0,0,medical,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,7,3,14,40
3264695,unknown,NaN,40.768167,-73.905433,unknown,unknown,unknown,0,0,0,0,0,0,0,0,unspecified,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,7,23,19,30
3266047,unknown,NaN,40.764417,-73.902904,unknown,unknown,unknown,3,0,0,0,0,0,3,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,7,25,16,20
3270621,unknown,NaN,40.766632,-73.889025,unknown,unknown,unknown,0,0,0,0,0,0,0,0,distraction,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,7,31,4,15
3271377,unknown,NaN,NaN,NaN,46 avenue,utopia parkway,unknown,0,0,0,0,0,0,0,0,driver_mistake,unspecified,not applicable,not applicable,not applicable,car/suv,car/suv,car/suv,car/suv,car/suv,2015,8,3,23,56