In [1426]:
import pandas as pd
import numpy as np

In [1427]:
pd.set_option('max_columns', 90)
pd.set_option('max_colwidth', 5000)

In [1428]:
df_crash = pd.read_csv("data_100000.csv", sep=',')

In [1429]:
df_crash.crash_date = df_crash.crash_date.astype('datetime64[ns]')

In [1430]:
df_crash.crash_time = df_crash.crash_time.astype('datetime64[ns]')

In [1431]:
df_crash['crash_year'] = df_crash.crash_date.dt.year
df_crash['crash_month'] = df_crash.crash_date.dt.month
df_crash['crash_day'] = df_crash.crash_date.dt.day
df_crash['crash_hour'] = df_crash.crash_time.dt.hour
df_crash['crash_minute'] = df_crash.crash_time.dt.minute

In [1432]:
df_crash = df_crash.drop(columns=['crash_date', 'crash_time', 'location'])

In [1433]:
df_crash.duplicated().any()

False

In [1434]:
lower_list = ['borough', 'on_street_name', 'off_street_name', 'cross_street_name', 'contributing_factor_vehicle_1', 'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3', 'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5', 'vehicle_type_code1', 'vehicle_type_code2', 'vehicle_type_code_3', 'vehicle_type_code_4', 'vehicle_type_code_5']

def to_lower(column_name:str):
    df_crash[column_name] = df_crash[column_name].apply(lambda x:x.lower() if type(x) == str else x)
    return df_crash[column_name]

for column_name in lower_list:
    df_crash[column_name] = to_lower(column_name)

In [1435]:
df_crash = df_crash.rename(columns={'vehicle_type_code1': 'vehicle_type_1', 'vehicle_type_code2': 'vehicle_type_2', 'vehicle_type_code_3': 'vehicle_type_3', 'vehicle_type_code_4': 'vehicle_type_4', 'vehicle_type_code_5': 'vehicle_type_5'})

In [1436]:
df_crash = df_crash.set_index(df_crash.collision_id)

In [1437]:
df_crash =  df_crash.drop(columns=['collision_id'])

In [1438]:
df_crash = df_crash.sort_index(ascending=True)

In [1439]:
factor_fill = ['contributing_factor_vehicle_1', 'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3', 'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5']

for col_name in factor_fill:
    df_crash[col_name] = df_crash[col_name].fillna('unspecified')

In [1440]:
vehicle_fill = ['vehicle_type_1', 'vehicle_type_2', 'vehicle_type_3', 'vehicle_type_4', 'vehicle_type_5']

for col_name in vehicle_fill:
    df_crash[col_name] = df_crash[col_name].fillna('not applicable')

In [1441]:
vehicle_list = ['ATV(all_terrain_vehicle)', 'bicycle', 'car/suv', 'ebike / escooter', 'truck/bus', 'motorcycle', 'other']

In [1442]:
vehicle_list = ['vehicle_type_1', 'vehicle_type_2',	'vehicle_type_3', 'vehicle_type_4', 'vehicle_type_5']

def consolidate(col_name):
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambul', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='amb', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambu', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='fdny ambul', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='nyc ambula', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambulence', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='abulance', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='almbulance', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambulence', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='white ambu', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='gen  ambul', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='abulace', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='leased amb', value='ambulance')
    df_crash[col_name] = df_crash[col_name].replace(to_replace='ambulace', value='ambulance')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash[col_name] = consolidate(col_name)

In [1443]:
replace_list = ['bus','van camper','box truck','tractor truck diesel','dump','tractor truck gasoline','tow truck / wrecker','concrete mixer','tract','beverage truck','refg', 'refrigerated van', 'box t', 'tanker', 'unkno', '4ds', 'com', 'armored truck', 'ladder 34','chassis cab','school bus','bulk agriculture', 'tower', 'self', 'truck', 'fire', 'white','trac', 'trail', 'open body','enclosed body - nonremovable enclosure', 'us po', 'usps', 'schoo','bulld', 'range', 'mta', 'well driller', 'picku', 'appor','fdny', 'lunch wagon', 'multi-wheeled vehicle', 'excav', 'nys a','firet', 'dirt', 'tow t','mta b','tow truck', 'uhaul', 'trl', 'back', 'towtr', 'sprin','trk', 'tk', 'fork', 'city', 'power', 'van t', 'mobil','comme', 'trlr','motorized home', 'cont', 'pickup with mounted camper', 'g spc', 'wineb', 'ltr', 'parce', 'forkl', 'hi ta','boxtr', 'pedicab', '35 ft', 'ut', 'backh', 'cat.', 'pu', 'const','prks', 'rmp v', 'paylo','flat', 'fdny truck','usps posta', 'firetruck','freight tr','freig delv', 'pc', 'mail truck','usps truck', 'fire truck', 'postal tru', 'commercial','fdny fire', 'enclosed body - removable enclosure','work van', 'lcomm', 'freig', 'government', 'subn whi','flatbed','camper tra', 'trailer','hrse', 'ems', 'back hoe', 'light trai','cargo van', 'f-250','fork lift', 'unk', 'trc', 'postal bus', 'nyc fd','f150xl pic', 'fire engin', 'mta bus', 'unknown','elec. unic', '1c', 'delivery t', 'gator', 'fdny engin','freight', 'ups truck','slingshot', 'road sweep','delivery v', 'utility ve', 'bucket tru', 'backhoe', 'tractor','moving van', '18 wheeler', 'usps van', 'garbage tr','livestock rack', 'freight fl', 'fdny #226', 'cross', 'food truck', 'dump truck','front-load', 'pumper','truck flat', 'tractor tr', 'delivery','truck van', 'psd', 'courier', 'swt', 'dilevery t','ford van', 'dark color','power shov', 'fdny ems','usps/govt', 'flatbed fr', 'can', 'cement tru', 'firtruck', 'f550','fdny ladde', 'box', 'livery vehicle','van', 'pick-up truck','polic', 'food', 'carry all','rv', 'garbage or refuse', 'p/sh', 'flat bed', 'cemen', 'delv', 'pk', 'intl', 'tuck', 'deliv','pas', 'moped', 'garba', 'enclo', 'movin', 'hand','uspos', 'stree', 'elect', 'post', 'hopper','campe', 'flat rack', 'dp', 'van (', 'fed e','glass rack', 'vanette', 'engin', 'work','jlg l', 'black','alumi','churc', 'utili','dirtb', 'rep', 'mack','pass', 'snow plow', 'ip', 'yello', 'trans', 'tra/r','detac', 'aspha', 'art m', 'mail', 'util wh', 'depar', 'spec-','ladder tru', 'schoolbus', '18 weeler', 'glnen', 'sweeper','tl', 'fd truck', 'sanitation', 'cargo truc', 'itas', 'lcom', 'hearse','frt', 'mailtruck', 'lma','skid loade','utility tr', 'tree cutte','van/transi', 'glp050vxev', 'ice cream', 'mobile', 'haul for h', 'commerical', 'freightlin', 'mopd','ems truck', 'nyc bus', 'us govt ve', 'special pu', 'frieghtlin', 'palfinger','internatio', 'fdny firet', 'mta truck','street cle','nyc firetr', 'moped elec', 'street swe','uhaul truc', 'u-haul', 'truck trai', 'tilt tande', 'revel', 'backhoe lo', 'transport','amazon spr','mini van', 'i1', 'fleet', 'constructi','left the s', 'nyc acs va', 'boom lift''carry all', 'van', 'garbage or refuse''moped', 'flat bed','food', 'pk', 'deliv','fdny firet', 'uhaul trai','uhaul box', 'unattached', 'concrete m', 'flat rack']
def trucks_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'truck/bus')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = trucks_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = trucks_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = trucks_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = trucks_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = trucks_cons('vehicle_type_5')

In [1444]:
replace_list = ['passenger vehicle', 'sport utility / station wagon', 'taxi','small com veh(4 tires) ', 'sedan','station wagon/sport utility vehicle', 'not applicable', 'bike','convertible','util','4d', '4 dr sedan', '2 dr sedan','3-door', 'e-350', 'comm.', 'bs','limou', 'mini', 'limo', 'e450', 'utility.','chevrolet', 'fusion','j1','chevy expr', 'ford sprin', 'wh ford co','unkn', 'suburban', 'oth''forlift', 'utility', 'smart car','sport utility / station wagon','passenger vehicle', 'taxi','small com veh(4 tires) ', 'station wagon/sport utility vehicle','sedan', '3-door', 'convertible','4 dr sedan','wagon', 'self-', 'ford','limo','util','2 dr sedan', 'rds','access a r', 'toyota', 'vehicle 2', 'ukn','passenger vehicle', 'taxi', 'sedan','station wagon/sport utility vehicle','convertible','4 dr sedan', 'limo', '3-door','sport utility / station wagon','station wagon/sport utility vehicle', 'sedan','taxi', 'convertible','toyot','4 dr sedan','limo','sedan', 'station wagon/sport utility vehicle','taxi','convertible', 'wagon']
def cars_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'car/suv')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = cars_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = cars_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = cars_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = cars_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = cars_cons('vehicle_type_5')

In [1445]:
replace_list = ['btm','minibike', 'scoot', 'stake or rack', 'minicycle', 'e-bik','e-sco', 'e bik', 'e-bike', 'dirt bike','e-scooter', 'e bike','e skate bo', '0', 'electric s', 'scooter', 'e revel sc', 'motor scoo', 'motorscoot', 'skateboard','message si', 'motor skat','e-unicycle','minibike', 'motorscooter', 'e-bik','scoot', 'e bik', 'e-sco','minicycle', 'stake or rack', 'e sco', 'skate','e350', 'subn', 'e250','e-ska', 'e-scooter', 'ebike', 'e-bike', 'scooter', 'c1', 'e-scoter', 'dirt bike','push scoot','gas scoote','razor scoo','e-skateboa', 'electric s', 'escooter','moped scoo', 'electric m', 'skateboard', 'dirtbike', 'uknown', 'e scooter', 'unknown ve', 'motor scoo','motorcycle', 'motorscooter', 'e-bik', 'e-bike', 'e-scooter','stake or rack','motorscooter','e-scooter','e-bike','e-scooter','motorscooter']
def bikes_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'ebike/escooter')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = bikes_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = bikes_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = bikes_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = bikes_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = bikes_cons('vehicle_type_5')

In [1446]:
replace_list = ['motorbike', 'vespa', 'motor', 'motorbike','motorbike']
def motorbike_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'motorbike')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = motorbike_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = motorbike_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = motorbike_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = motorbike_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = motorbike_cons('vehicle_type_5')

In [1447]:

replace_list = ['pick-','pick up tr', 'pick-up tr', 'pick up','suv','pick','pick up','pick-up tr','pickup', 'suv', 'pick truck', 'ram','4dsd','pick up tr', 'trailor', 'flatbed tr']
def atv_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'atv')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = atv_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = atv_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = atv_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = atv_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = atv_cons('vehicle_type_5')

In [1448]:
replace_list = ['other','posta', 'lift boom', 'winne', 'bobca', 'golf','golf cart', 'forklift', 'mechanical', 'cat', 'fd ladder','bobcat for', 'horse', 'dot equipm', 'go kart', 'john deere','oth', 'drill rig', 'lawnmower', 'forlift','lift boom', 'bobca', 'atv', 'crane', 'pallet','john', 'cat32', 'train', 'lift', 'boom', 'horse', 'golf cart','forklift', 't630 forkl', 'jetski', 'bob cat', 'escovator','john deere', 'lawn mower', 'folk lift', 'boom lift','lift boom', 'pallet']
def other_cons(col_name):
    df_crash[col_name] = df_crash[col_name].replace(replace_list, 'other')
    return df_crash[col_name]

for col_name in vehicle_list:
    df_crash['vehicle_type_1'] = other_cons('vehicle_type_1')
    df_crash['vehicle_type_2'] = other_cons('vehicle_type_2')
    df_crash['vehicle_type_3'] = other_cons('vehicle_type_3')
    df_crash['vehicle_type_4'] = other_cons('vehicle_type_4')
    df_crash['vehicle_type_5'] = other_cons('vehicle_type_5')

In [1449]:
df_crash.vehicle_type_1.unique()

array(['car/suv', 'other', 'truck/bus', 'ebike/escooter', 'ambulance',
       'motorbike'], dtype=object)

In [1450]:
df_crash.vehicle_type_2.unique()

array(['car/suv', 'other', 'truck/bus', 'ebike/escooter', 'ambulance',
       'motorbike'], dtype=object)

In [1451]:
df_crash.vehicle_type_3.unique()

array(['car/suv', 'truck/bus', 'ebike/escooter', 'motorbike', 'ambulance',
       'other'], dtype=object)

In [1452]:
df_crash.vehicle_type_4.unique()

array(['car/suv', 'other', 'truck/bus', 'ebike/escooter', 'ambulance'],
      dtype=object)

In [1453]:
df_crash.vehicle_type_5.unique()

array(['car/suv', 'truck/bus', 'ambulance', 'ebike/escooter'],
      dtype=object)

In [1454]:
df_crash.tail()

,borough,zip_code,latitude,longitude,on_street_name,off_street_name,cross_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,vehicle_type_1,vehicle_type_2,vehicle_type_3,vehicle_type_4,vehicle_type_5,crash_year,crash_month,crash_day,crash_hour,crash_minute
collision_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4353663,brooklyn,11201.0,40.689830,-73.978630,de kalb avenue,ashland place,NaN,1,0,0,0,1,0,0,0,driver inattention/distraction,driver inattention/distraction,unspecified,unspecified,unspecified,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,21,8,55
4353672,brooklyn,11236.0,40.645958,-73.906130,NaN,NaN,992 east 95 street,0,0,0,0,0,0,0,0,driver inattention/distraction,unspecified,unspecified,unspecified,unspecified,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,29,16,0
4353701,manhattan,10029.0,NaN,NaN,east 99 street,lexington avenue,NaN,1,0,0,0,1,0,0,0,traffic control disregarded,unspecified,unspecified,unspecified,unspecified,car/suv,ebike/escooter,car/suv,car/suv,car/suv,2020,9,29,19,11
4353705,bronx,10461.0,40.849342,-73.850610,NaN,NaN,1716 williamsbridge road,0,0,0,0,0,0,0,0,unspecified,unspecified,unspecified,unspecified,unspecified,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,29,14,0
4353706,NaN,NaN,40.790623,-73.942444,2 avenue,NaN,NaN,1,0,0,0,0,0,1,0,following too closely,unspecified,unspecified,unspecified,unspecified,car/suv,car/suv,car/suv,car/suv,car/suv,2020,9,24,18,30

In [1455]:
replace_list = ['contributing_factor_vehicle_1', 'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3', 'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5']

distraction = ['driver inattention/distraction','passenger distraction','fell asleep','outside car distraction',
                   'fatigued/drowsy','cell phone (hand-held)','using on board navigation device',
                   'tinted windows','eating or drinking', 'other electronic device', 'cell phone (hands-free)',
                   'listening/using headphones']
driver_mistake = ['following too closely','failure to yield right-of-way','backing unsafely',
                      'passing or lane usage improper','passing too closely','unsafe lane changing',
                      'turning improperly','driver inexperience', 'failure to keep right',
                      'driverless/runaway vehicle', 'oversized vehicle']
illegal_action = ['unsafe speed','alcohol involvement','traffic control disregarded','aggressive driving/road rage',
                      'drugs (illegal)']
other_involvement =  ['other vehicular','reaction to uninvolved vehicle', 'animals action',
                          'view obstructed/limited','pedestrian/bicyclist/other pedestrian error/confusion',
                           'glare','vehicle vandalism']
bad_road_infrastructure = ['pavement slippery', 'obstruction/debris','pavement defective',
                               'other lighting defects']
car_failures = ['brakes defective', 'steering failure', 'tire failure/inadequate',
                    'traffic control device improper/non-working', 'lane marking improper/inadequate',
                    'tow hitch defective','headlights defective', 'shoulders defective/improper',
                    'windshield inadequate']
medical = ['lost consciousness', 'illnes','accelerator defective','physical disability','prescription medication']

def factor_replace(col_name):
    df_crash[col_name] = df_crash[col_name].replace(distraction, 'distraction')
    df_crash[col_name] = df_crash[col_name].replace(driver_mistake, 'driver_mistake')
    df_crash[col_name] = df_crash[col_name].replace(illegal_action, 'illegal_action')
    df_crash[col_name] = df_crash[col_name].replace(other_involvement, 'other_involv')
    df_crash[col_name] = df_crash[col_name].replace(bad_road_infrastructure, 'bad_road')
    df_crash[col_name] = df_crash[col_name].replace(car_failures, 'mech_fail')
    df_crash[col_name] = df_crash[col_name].replace(medical, 'medical')
    return df_crash[col_name]

for col_name in replace_list:
    df_crash[col_name] = factor_replace(col_name)

In [1456]:
df_crash_2 = df_crash.copy()

In [1457]:
df_crash_2 = df_crash_2.rename(columns={'vehicle_type_1': 'veh_1', 'vehicle_type_2': 'veh_2', 'vehicle_type_3': 'veh_3', 'vehicle_type_4': 'veh_4', 'vehicle_type_5': 'veh_5'})

In [1458]:
df_crash_2 = pd.get_dummies(df_crash_2, columns = ['veh_1', 'veh_2', 'veh_3', 'veh_4', 'veh_5'])

In [1459]:
df_crash_2 = df_crash_2.drop(columns=['borough','zip_code', 'on_street_name', 'off_street_name', 'cross_street_name', 'number_of_persons_injured', 'number_of_persons_killed', 'crash_minute'])

In [1460]:
df_crash_2 = df_crash_2.rename(columns={'contributing_factor_vehicle_1': 'factor_veh_1', 'contributing_factor_vehicle_2': 'factor_veh_2', 'contributing_factor_vehicle_3': 'factor_veh_3', 'contributing_factor_vehicle_4': 'factor_veh_4', 'contributing_factor_vehicle_5': 'factor_veh_5'})

In [1461]:
df_crash_2 = pd.get_dummies(df_crash_2, columns = ['factor_veh_1', 'factor_veh_2', 'factor_veh_3', 'factor_veh_4', 'factor_veh_5'])

In [1462]:
df_crash_2.dropna(axis=0, inplace=True)

In [1463]:
df_crash_2.head(10)

,latitude,longitude,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,crash_year,crash_month,crash_day,crash_hour,veh_1_ambulance,veh_1_car/suv,veh_1_ebike/escooter,veh_1_motorbike,veh_1_other,veh_1_truck/bus,veh_2_ambulance,veh_2_car/suv,veh_2_ebike/escooter,veh_2_motorbike,veh_2_other,veh_2_truck/bus,veh_3_ambulance,veh_3_car/suv,veh_3_ebike/escooter,veh_3_motorbike,veh_3_other,veh_3_truck/bus,veh_4_ambulance,veh_4_car/suv,veh_4_ebike/escooter,veh_4_other,veh_4_truck/bus,veh_5_ambulance,veh_5_car/suv,veh_5_ebike/escooter,veh_5_truck/bus,factor_veh_1_bad_road,factor_veh_1_distraction,factor_veh_1_driver_mistake,factor_veh_1_illegal_action,factor_veh_1_mech_fail,factor_veh_1_medical,factor_veh_1_other_involv,factor_veh_1_unspecified,factor_veh_2_bad_road,factor_veh_2_distraction,factor_veh_2_driver_mistake,factor_veh_2_illegal_action,factor_veh_2_mech_fail,factor_veh_2_medical,factor_veh_2_other_involv,factor_veh_2_unspecified,factor_veh_3_bad_road,factor_veh_3_distraction,factor_veh_3_driver_mistake,factor_veh_3_illegal_action,factor_veh_3_mech_fail,factor_veh_3_other_involv,factor_veh_3_unspecified,factor_veh_4_bad_road,factor_veh_4_distraction,factor_veh_4_driver_mistake,factor_veh_4_illegal_action,factor_veh_4_other_involv,factor_veh_4_unspecified,factor_veh_5_bad_road,factor_veh_5_distraction,factor_veh_5_driver_mistake,factor_veh_5_illegal_action,factor_veh_5_other_involv,factor_veh_5_unspecified
collision_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
225766,40.746435,-73.703790,1,0,0,0,0,0,2013,10,15,18,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2809808,40.869761,-73.844877,0,0,0,0,0,0,2014,10,17,19,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2874775,40.862498,-73.934185,0,0,0,0,0,0,2013,4,23,22,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2879367,40.808193,-73.904886,0,0,0,0,0,0,2013,4,13,17,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2912981,40.860198,-73.828790,0,0,0,0,0,0,2013,3,23,21,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2957510,40.614812,-74.039816,0,0,0,0,5,0,2013,3,24,5,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2976167,40.678100,-74.002339,0,0,0,0,0,0,2013,4,14,12,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
3017476,40.665840,-73.757385,0,0,0,0,0,0,2013,4,22,10,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
3222266,40.781667,-73.986689,0,0,0,0,0,0,2015,5,15,18,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
3224230,40.851501,-73.942523,0,0,0,0,0,0,2015,5,16,4,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1

In [1464]:
df_crash_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91965 entries, 225766 to 4353706
Data columns (total 74 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   latitude                       91965 non-null  float64
 1   longitude                      91965 non-null  float64
 2   number_of_pedestrians_injured  91965 non-null  int64
 3   number_of_pedestrians_killed   91965 non-null  int64
 4   number_of_cyclist_injured      91965 non-null  int64
 5   number_of_cyclist_killed       91965 non-null  int64
 6   number_of_motorist_injured     91965 non-null  int64
 7   number_of_motorist_killed      91965 non-null  int64
 8   crash_year                     91965 non-null  int64
 9   crash_month                    91965 non-null  int64
 10  crash_day                      91965 non-null  int64
 11  crash_hour                     91965 non-null  int64
 12  veh_1_ambulance                91965 non-null  uint8
 13  veh_1_car/suv                  91965 non-null  uint8
 14  veh_1_ebike/escooter           91965 non-null  uint8
 15  veh_1_motorbike                91965 non-null  uint8
 16  veh_1_other                    91965 non-null  uint8
 17  veh_1_truck/bus                91965 non-null  uint8
 18  veh_2_ambulance                91965 non-null  uint8
 19  veh_2_car/suv                  91965 non-null  uint8
 20  veh_2_ebike/escooter           91965 non-null  uint8
 21  veh_2_motorbike                91965 non-null  uint8
 22  veh_2_other                    91965 non-null  uint8
 23  veh_2_truck/bus                91965 non-null  uint8
 24  veh_3_ambulance                91965 non-null  uint8
 25  veh_3_car/suv                  91965 non-null  uint8
 26  veh_3_ebike/escooter           91965 non-null  uint8
 27  veh_3_motorbike                91965 non-null  uint8
 28  veh_3_other                    91965 non-null  uint8
 29  veh_3_truck/bus                91965 non-null  uint8
 30  veh_4_ambulance                91965 non-null  uint8
 31  veh_4_car/suv                  91965 non-null  uint8
 32  veh_4_ebike/escooter           91965 non-null  uint8
 33  veh_4_other                    91965 non-null  uint8
 34  veh_4_truck/bus                91965 non-null  uint8
 35  veh_5_ambulance                91965 non-null  uint8
 36  veh_5_car/suv                  91965 non-null  uint8
 37  veh_5_ebike/escooter           91965 non-null  uint8
 38  veh_5_truck/bus                91965 non-null  uint8
 39  factor_veh_1_bad_road          91965 non-null  uint8
 40  factor_veh_1_distraction       91965 non-null  uint8
 41  factor_veh_1_driver_mistake    91965 non-null  uint8
 42  factor_veh_1_illegal_action    91965 non-null  uint8
 43  factor_veh_1_mech_fail         91965 non-null  uint8
 44  factor_veh_1_medical           91965 non-null  uint8
 45  factor_veh_1_other_involv      91965 non-null  uint8
 46  factor_veh_1_unspecified       91965 non-null  uint8
 47  factor_veh_2_bad_road          91965 non-null  uint8
 48  factor_veh_2_distraction       91965 non-null  uint8
 49  factor_veh_2_driver_mistake    91965 non-null  uint8
 50  factor_veh_2_illegal_action    91965 non-null  uint8
 51  factor_veh_2_mech_fail         91965 non-null  uint8
 52  factor_veh_2_medical           91965 non-null  uint8
 53  factor_veh_2_other_involv      91965 non-null  uint8
 54  factor_veh_2_unspecified       91965 non-null  uint8
 55  factor_veh_3_bad_road          91965 non-null  uint8
 56  factor_veh_3_distraction       91965 non-null  uint8
 57  factor_veh_3_driver_mistake    91965 non-null  uint8
 58  factor_veh_3_illegal_action    91965 non-null  uint8
 59  factor_veh_3_mech_fail         91965 non-null  uint8
 60  factor_veh_3_other_involv      91965 non-null  uint8
 61  factor_veh_3_unspecified       91965 non-null  uint8
 62  factor_veh_4_bad_road          91965 non-null  uint8
 63  factor_veh_4_distraction       91965 non-null  uint8
 64  factor_veh_4_driver_mistake    91965 non-null  uint8
 65  factor_veh_4_illegal_action    91965 non-null  uint8
 66  factor_veh_4_other_involv      91965 non-null  uint8
 67  factor_veh_4_unspecified       91965 non-null  uint8
 68  factor_veh_5_bad_road          91965 non-null  uint8
 69  factor_veh_5_distraction       91965 non-null  uint8
 70  factor_veh_5_driver_mistake    91965 non-null  uint8
 71  factor_veh_5_illegal_action    91965 non-null  uint8
 72  factor_veh_5_other_involv      91965 non-null  uint8
 73  factor_veh_5_unspecified       91965 non-null  uint8
dtypes: float64(2), int64(10), uint8(62)
memory usage: 14.6 MB

In [1465]:
df_crash_2.to_csv('nyc_crash_dataset.csv')